### PR TITLE
Contacts-api use Personio-client

### PR DESCRIPTION
**Pull request by ArktinenSieni**
Progress so far. How does it look?

### CODE REVIEW

**Comment by ArktinenSieni** [comment]
Rebased and dropped some Planmill stuff. `addFlowdockInfo` is already in use at row 68. Did you @phadej mean to use Flowdock's avatar as `contactThumb` or `contactImage`?

**Comment by phadej** [comment]
ah, I meant `addFumInfo`, and use it's pictures as `contactThumb` and `contactImage`. Sorry for mess-up, shouldn't write in hurry

**Comment by phadej** [comment]
red  :/

**Comment by ArktinenSieni** [comment]
Now it passed ^^ @phadej

**Comment by phadej** [comment]
Great, I'll fine-tune it a bit and deploy. Good job.

**Pull request merged**
