### PR TITLE
FUM login relaxation

### PR DESCRIPTION
**Pull request by thaiscristine**
We are removing the parseLogin function and its usage throughout the code.

### CODE REVIEW

**Comment by thaiscristine** [comment]
Hi @mixman! I added you as a reviewer to this PR to give some insight about this change if you have some spare time. I don't have a clear picture of how to test this change. You can provide some thoughts on it as well.

**Review by lumicake — COMMENTED** [review]
Removing all the constraints is definitely a laxation of the constraints :D And with this change it seems like PersonioIDs would work as identifiers in the future. Anything would, pretty much. Will the logic for prepending `"p"` to Personio IDs in the future be added here, to `parseLogin`?

**Comment by mixman** [comment]
Parsing is relaxed indeed (no checks). Then remains generating the login for Personio profiles ("p"+ID) when none is provided by Personio.

**Comment by jvanbruegge** [comment]
This was superseded by #896

**Pull request closed without merging**
